apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-credentials
  namespace: default
spec:
  refreshInterval: "30s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_API_KEY
      remoteRef:
        key: secret/data/app
        property: api_key
