apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-gpg-keys-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  9905D095C1B30594: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBGoqXqwBEACmOqMu8rORZCTSe70kJ75GAK+55wQUMBoNuu2V/MPkWRhHb+TP
    HPrQCLmmSAzMUnkj54jNK7x+/TS3DQi9cbyAVCaiR2TDGYSM5wMZz8+OoUt+PzcI
    nkX99jCCacAp1J8ixi1pgZ0xeQ9YPDcA/8BoGhFDYH0TZs0KL6D1uwRcQqbwHQSX
    k25cJjUSTPXMmXjWKS71fXgl4LI7oeM+tcLBh69wa57fZlbX0ZbQuaBc8vXh77b8
    nYSVkscchqQXRW0/9NysViexA3wCmmOrc09jQn2TmC/iF3lmAXBWTijgtS83+cif
    zA6M6nrKbWAvDaiAE+Gze/KDLlRMg6+O9FaTIz6hGu4mUIyimKQywBJq6G65yevb
    EivDsr2Yjzaz+A6kMeKR/oDJMABMkO8LBVw4wYH6ig9v3JxnbXVClfqBjJ2kmJrr
    +0iLOyy86gSBTj5JC3gXjT8K8L33vBGkoc9Xy9sq4s4ul22DeeGDSj/h5VSszVEK
    ehQmwAQG7ovlvt1x7jcDCc56lMZi0aShHqrSb7dDpv7qryZS2o4gVAsOdJYsfzDZ
    1iHDbz7N4z0BkIB61vtu5BPJWx2AZ58XpAGUiwBeEtz/A9WColX8I5n567MtShVw
    l8iZGqi7E3FatUZd3vnDkqnpTJ4lN4Lcq11gYaxbhAy66TpidsRQVMqrZQARAQAB
    tDZwYXJ0aCAoc2VjdXJlcGlwZWxpbmUtYXJnb2NkKSA8cGFydGguMjI0NDBAa25p
    dC5hYy5pbj6JAk4EEwEIADgWIQTi1zsHs6VcfRvWPfCZBdCVwbMFlAUCaiperAIb
    AwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRCZBdCVwbMFlP6KD/9FvElH1xf6
    Y34GdQxFbtH7cwWP5qxd7L7nMWOWO37ajBQikTW4FiRLM1TUMxwZY5iad2vQRXao
    5B3nwoRUSlGH1jqn3HKLcd2BvZyjjsbulHVdaAPySqC0xZPQGGjgTTnPJrxSIcxi
    FCfbOh38PUmvl7zMGOPx2bjD8ca6jj9JG0/Tv4IopRi51a0D9LYvvYUs2qcyd0WV
    OY4T+HCVIYV+877BFiGHRLpzM9501bRoaaBHW9/bG9XDmRFN7t5MTiQ2dqjiPfk+
    dtRexXS02shml93+xLy7Tep/ifJ5aK0PWSdWX8/IEvE14tMWmqCeSz+2X0o6svJl
    0aLB6LBVaj03hBktDky7IjKJhUfTLHIgXyn0IsrKL/99gnb7ObFUxRo2q1A4bhfD
    wPCuenBaG2PK2D+4NMEoBwEy5F7MTTZ9744VkfzhmTaprzv1k4KwEAV5b7mYud9z
    LmhpzQbWeTJdA+CHzhpIWZQ40+gOU+vHjLyz/MbU6kphU1XAkEOH1dP/LFeHNVTq
    nhobn3RZnZzgJ0IdTyJcK2ETdchgfzM2T1EO9+XYtR2HNhuLluZH4QrhxHrhW4W4
    qKwxRlZcKcsPLHYUIin5fCKve8x9ZQasOVZxLpnOlgtaX5AgK4goR9ivE2/Bdof3
    6or89CW77sN9b8ffDvGk+xMJWrlBBm2S0rkCDQRqKl6sARAA1Nva2755Ve4cuOnF
    IjC+INmSGbDXEyad2+YzKGn2CJnpDQW17xpqU4Y2MqtM0Qdq9LMpndlD5kQHN9rp
    CgfZ82VACO/PRonHTebvi+7r+szV3QjrFLN3OLsGsDnh8rUDV5CsTNi71uyv7Jp1
    h7+QjrRntQrLgbB68jo0qi0ACiAtzsmIYjs7AF44bcyacUdqC8PCBKJsc7AIhKfe
    wWz5rzRX1Me0yyl4uPzadnM8PwPAijSMoeTe8nDa16w8tjklQCN8xqUxvf5TYi6I
    W47c2aAfGm8ijqE2w4bMIbJuZ+ahnIvlvmKL4cgICMqLBObzxKAJFL4YDLr68E2M
    1NiGiE2/cGxCjeBdKk4S04VR+0rpFbeTPdNIpJH1gmRG4dngulbhfTasTDJKzxDW
    EYGhcAAUzv7+SABUDA3guvFs2WzciReeknLBsYlEjh03VIBPly2dAXab3culo5iU
    o7P8mPhgJs5bfm9p2c8W2g6//ZJrpB0vDxRhzUpjn+suZIJvxImRrPUmxF5yLaWv
    Jtd75v3/6USEE1U0GE5iSVVfawFGx7sYc5DUNkZqsszw2gnFKGUYhqaHdhDuPn4G
    eKJxP25AuzMQ2WIRHGSq53pBweGFbz5GLEC/zxO+Pex7BHd46wLASg6DL0jO+bW+
    jsSRGLHY0K7LA9CFcC6s1fiRv60AEQEAAYkCNgQYAQgAIBYhBOLXOwezpVx9G9Y9
    8JkF0JXBswWUBQJqKl6sAhsMAAoJEJkF0JXBswWU8+oP/0kZhyUfIsas0bcm6fZQ
    TF5SvifAXdFZsU1VKdULXKplLSpkXZ08LAfREesnmWroa37oN/JK//FEfTrj/T2h
    AiLJ+23uHMLIUiMpuinVuHAjXYVbTkhQ25tUWNu7lRm00OhZJwbvIS4PEM41CPUV
    s3jbPQnmCaCf/FhSUi6A6BxB5cfyG2P0j1yvTR+j33oEXWnB9wmGU2EeYmqBLxTO
    w0pBPDSCzefNoF998cwHv/tSvoQ6/BmU4Q1Y4JGKVQVEbEnqYGX+CYO6Rr2MIF/D
    ycHV/2o5I9KE3qGsasIKgIpN6j9ddXQ2vsevO/fzB2JMo5Oxjbew/tLXEvopCphR
    D7LcMARBY+75l3b8NkkNn5gShARsfxmVon2iYX9VhohCFmA4ZJqZfPNw/j6u6JeL
    DSMB3gaWdv8FH2/0+qNCSg1uz586pfmrYe1mN+ccNXwjkH00MsNiHgFipcS880tI
    7f2e8BktQCC4T3Qc12HtCF/q4x/Qhhn3HJrLqCiJXkpLvfgPZjrqCMQKV++bzmPk
    XGr0FPd93XfrQ+2Ty/bhIlub3qu4dE24OyGaCWY6bIfZTQpbtiZlOEi08vOAZ4tB
    tPDSSReqUoS3m1Zu7KRmWEC7SPFH5aUpr3kfo7G9mFLkOqRMhLAsK3St6Wb/8QAh
    kNgLOfyghS5hMoHTOvLS4PHH
    =MFOc
    -----END PGP PUBLIC KEY BLOCK-----
  4AEE18F83AFDEB23: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    xsBNBFmUaEEBCACzXTDt6ZnyaVtueZASBzgnAmK13q9Urgch+sKYeIhdymjuMQta
    x15OklctmrZtqre5kwPUosG3/B2/ikuPYElcHgGPL4uL5Em6S5C/oozfkYzhwRrT
    SQzvYjsE4I34To4UdE9KA97wrQjGoz2Bx72WDLyWwctD3DKQtYeHXswXXtXwKfjQ
    7Fy4+Bf5IPh76dA8NJ6UtjjLIDlKqdxLW4atHe6xWFaJ+XdLUtsAroZcXBeWDCPa
    buXCDscJcLJRKZVc62gOZXXtPfoHqvUPp3nuLA4YjH9bphbrMWMf810Wxz9JTd3v
    yWgGqNY0zbBqeZoGv+TuExlRHT8ASGFS9SVDABEBAAHNNUdpdEh1YiAod2ViLWZs
    b3cgY29tbWl0IHNpZ25pbmcpIDxub3JlcGx5QGdpdGh1Yi5jb20+wsBoBBMBCAAc
    BQJZlGhBCRBK7hj4Ov3rIwIbAwUJDBJ3/wIZAQAA0O4IAJd0k8M+urETyMvTqNTj
    /U6nbqyOdKE4V93uUj5G7sNTfno7wod/Qjj6Zv5KodvA93HmEdQqsmVq5YJ5KGiw
    cmGCpd/GqJRPaYSY0hSUSBqYHiHLusCJkPBpQTBhcEMtfVCB2J6fVeoX2DV0K1xf
    CGblrSVB0viAxUMnmL5C55RuvbYZsTu8szXhkvIR96CtWbJ8QGaEf1/KSpWz8ept
    Y/omf3UPfvdOjnsxc8jVEqPNaR9xC6Q6t53rBa/XgMY6IYyesnyYnc5O6JuexUFa
    VjykRFtAiYfDaMARpXOmgMm0lhoBRKb/uMUaN3CSYTmE4pZweJcUi7eWgmoQljX2
    ut6ZAg0EZabFdgEQALI37i+IVAzpBCgqvQDZbSsZ0yhtMnA5myjZA+l7BvIGy4ve
    s1bk6YetbBcCE8o2pQjI7N2rwyhLGhNO6ouSyhqGLEQv9fafKE4HFH0aRjP+gj1H
    edhwtFoVChImhV863rWimQtTNtYB6GluBPwQqWfwmwQ2rT7ScOVZCLSHZD2gaaqW
    BXOyTCZVnwt7K/gyDuE3qzDJnuahl+SSkPn5TtnZdW6sLORJJ+DjNvaUxEsmizZ4
    IBzvj0QKxfS3s4F+0X5iqCMheLFeybZGtSq9Tjs6Q61l4CG8Bh6dsLemv0WFrk3G
    gFQRr7XUwr1bo5xGHC/FUJSsxRHoVNJnIL/9WldNO2tGU6qlTnAYxs/fOmf2B6o5
    cKXysXv7WAA8b+j5AVBMGxUSu7CLglaiCJC5DI7AAiUV7/t29rFZkam//Jbb4veC
    4vvFocoVUaxrKGWK1BDldr4/WJKApJcPJF4Jtai1+oB6ak/JIjbkseHdJxcjo2B0
    dKtIFoWiPAB+DFs9MRDpp0iwocJCh+ucus1rdQ54YMaI44rRphXeOIQMYCi5q2Q1
    /arzkSiyPV/2VoKoAfdgskPt1xKd7WIKErmpFMHIy8jJ5IPQ1s2dUwU4alfJLJa0
    pvaV2m7wBYFAmwmz0WZgFxYAYEDamn4jFoKfqsEgcixRUVE3w5VkqwSwGRbLABEB
    AAG0G0dpdEh1YiA8bm9yZXBseUBnaXRodWIuY29tPokCTgQTAQoAOBYhBJaEeaGv
    +SfjfRpWa7VpDu67lSGUBQJlpsV2AhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheA
    AAoJELVpDu67lSGUgy4QAKW9XAL416iKrQB2LElmxqAoenHVCswlau0xGLh5dVNN
    p5f4/W6eEL8CZI7hfF3e5Gh6Me99aHgXSCK1QnxcqCJ6Oea4ZyrsNu3k6g7Um5ca
    VbYFD4yIahhXDYHSw6FYM2sgFY479YvgvKRwacC2tFfChLRbHgwLJ3O1dBjmVycJ
    Zpbyu+7taZ26g6KQfgcj3uuo3nz3p1ziIEpLHwtl/7joNEIIP/lJ8AKmUHPiGznN
    6fxMvzN37PGMWtdvOi1rSNIMQYr1YY7jPnlLbFJwLrO/q/cGPU5HwGzlqh0a2ZqY
    dnuwT3DREmgJ83H71xH+sTzZKs5oGlVTu6st7iWDvNpo2GoN01XzKa5caYglqsOC
    uZ6IHlsdL50sXMtSROCi3hEWU9r1sWIm4k3pNz20y7lElD2X/MqbEMcgpawCV7lH
    rm7MSrTgu6BNAF0SisbF9AKwXaBr2dwpMMyIBOFZO9mk4/c0n9q2FlGY4GkbgH2J
    HqulFTwX/4yiQbh8gzCe+06FZAWITN1OQntTkkCQ+1MCZPf+bOfC08RTsOsVZIYB
    2qAgw6XE0IF4a+PAtHSoYftwH2ocMY2gMuSNpQWm7m0+/j+K+RBoeUcnGNPQgszq
    N60IDMqkqHjyubrm2aslfopWmPSvaQoyxwV/uztdo+UI0IV2z9gD7Sm49vMkpYp8
    =uMz0
    -----END PGP PUBLIC KEY BLOCK-----
